### PR TITLE
backend integration

### PR DESCRIPTION
**Pull request by pAditya198**

### CODE REVIEW

**Comment by pAditya198** [comment]
rebase and merge krna

**Comment by thepushkarp** [comment]
Screenshot from 2020-06-20 22-49-38

@pAditya198, I'm getting this error

**Comment by pAditya198** [comment]
I've taken the lastest pull tho

**Comment by thepushkarp** [comment]
This is appearing just for Rebasing. Merging can be done fine.

**Comment by pAditya198** [comment]
Is there some fix to this?

**Comment by thepushkarp** [comment]
No idea. Probably commits in this PR has conflicting changes among themselves.

**Comment by pAditya198** [comment]
Say no more you'll confuse me

**Pull request closed without merging**
